### ISSUE TITLE
Code Release ? 

### ISSUE THREAD

**Issue by AMEERAZAM08** [SilasAntonisen/PolySinger#1]

**Comment by SilasAntonisen** [comment]
Hello and thank you for your interest in my work!
I am currently revising my scripts to improve their quality and readability.
My plan is to have a code release ready by the time of the ISMIR 2024 conference which will take place from the 10th till the 14th of November. Of course, if I am happy with my results before the conference, I will release it earlier.

**Comment by SilasAntonisen** [comment]
The code has been released! :)
